# 서버 포트 설정
server:
  port: 8080

spring:
  # 애플리케이션 이름 및 환경 설정
  application:
    name: freeSite
  output:
    ansi:
      enabled: always

  # Spring 데이터베이스 설정
  datasource:
    url: jdbc:h2:tcp://localhost/~/freeSite
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show-sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 500
          fetch_size: 500
          batch_versioned_data: true

springdoc:
  packages-to-scan: com.colabear754.springdoc_example.controllers
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    enabled: true # Swagger UI를 활성화합니다.
    path: /index.html
    display-request-duration: true
    operations-sorter: alpha

jwt:
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret' 이라는 문자열을 base64로 인코딩
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  expirationMs: 86400	# 초

kakao:
    req-url: https://kauth.kakao.com/oauth/token
    getUser-url: https://kapi.kakao.com/v2/user/me
    redirect-url: http://localhost:3000/kakao/callback
    apikey: 4a61ea8b549b24a89de92ba2670a39e9
    secret: yOdfaU3DfrLlQ1ulweFKFIxhBMi3SL5b

# 로깅 설정
logging:
  level:
    root: info
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([${spring.application.name},%X{trace_id},%X{span_id}]) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m %n%wEx"